name = "Igloo"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = ["blog", "personal", "portfolio", "responsive", "customizable"]
features = []
min_version = "0.117.0"

[author]
  name = "Athanasia Monika Mowinckel"
  homepage = "https://drmowinckels.io/"

