# Theme config.
baseURL = "."
languageCode = "en-us"
title = "Igloo"
theme = "hugo-igloo"

enforce_ssl             = true
builddrafts             = false  # Include pages with draft status of true
canonifyurls            = true   # Turns relative urls into absolutet]


[[menu.main]]
   name    = "About"
   url     = "about"
   weight  = 1
[[menu.main]]
   name    = "About sub1"
   url     = "#"
   weight  = 1
   parent  = "About"
[[menu.main]]
   name    = "About sub2"
   url     = "#"
   weight  = 2
   parent  = "About"
[[menu.main]]
   name    = "Blog"
   url     = "blog"
   weight  = 2
[[menu.main]]
   name    = "Projects"
   url     = "projects"
   weight  = 4
[[menu.main]]
   name    = "Timeline"
   url     = "timeline"
   weight  = 5


# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"
  category = "categories"

[params]
    subtitle       = "an icicle experience"
    showRSSButton  = false                   # Show rss button in navigation
    dateFormat     = "Jan 2, 2006"

    [params.footerSection]
        title = "Footer Title"
        content = "This is the content for the custom footer section."

    [params.aesthetics]
        # icicle, mint, barbie,
        # dune, vlad, poppy,
        # moss, paper, plum, 
        # violet, water
        design = "icicle"  

        # Or set your own custom colours
         # primary = "#b38e65"
         # secondary = "#00ff00"
         # emphasis = "#ff00ff"
         # muted = "#00ffff"

        # Include custom css files placed under assets/css/
        customCSS      = [] 

        # square, rabbet, bevel
        # hexagon, octagon,
        thumbShape     = "hexagon"
        favicon        = "favicon.png"      # Path to favicon file from the assets/ directory
        logo           = "/images/theme.png"

    [params.analytics]
    [params.analytics.plausible]
        domain = ""

    [params.blog]
        citation = true

    [params.giscus]
        repo = ""
        repo_id = ""
        category = "Comments"
        category_id = ""
        mapping = "pathname"
        reactions_enabled = "1"
        emit_metadata = "0"
        #theme = "/css/giscus.css"
        theme = "light"
        lang = "en"

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = ""
        icon  = "mastodon" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = ""
        icon  = "twitter-square" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = ""
        icon  = "github-square" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = ""
        icon  = "linkedin" # icon name without the 'fa-'
        icon_pack = "fab"

    [[params.social]]
        url   = ""
        icon  = "stack-overflow" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = ""
        icon  = "orcid" # icon name without the 'fa-'
        icon_pack = "fa-brands"
    [[params.social]]
        url   = ""
        icon  = "researchgate" # icon name without the 'fa-'
        icon_pack = "fab"

