name: Hugo Build

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.117.0' 
        extended: true

    - name: Build Hugo site
      run: |
        cd exampleSite && \
        hugo \
          --themesDir ../.. \
          --baseURL https://${{ github.repository_owner }}.github.io/$(basename ${{ github.repository }})

    - name: Deploy production 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: ./exampleSite/public