name: Hugo Build

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.117.0' 
        extended: true

    - name: Extract GitHub Pages link
      run: |
        repo="${{ github.repository }}"
        owner=$(echo $repo | sed -n 's/^\(.*\)\/.*/\1/p')
        repo_name=$(echo $repo | sed -n 's/.*\/\([^/]*\)$/\1/p')
        github_pages_link="https://$owner.github.io/$repo_name/"
        echo "gh-pages=$github_pages_link" >> $GITHUB_ENV

    - name: Build Hugo site
      run: |
        cd exampleSite && \
        hugo \
          --themesDir ../.. \
          --baseURL ${{ env.gh-pages }}

    - name: Deploy production 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: ./exampleSite/public