name: Hugo Build

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.117.0' 
        extended: true

    - name: Extract GitHub Pages link
      run: |
        repo_fullname="${{ github.repository }}"
        owner=$(echo $repo_fullname | sed -n 's/^\(.*\)\/.*/\1/p')
        repo_name=$(echo $repo_fullname | sed -n 's/.*\/\([^/]*\)$/\1/p')
        github_pages_link="https://$owner.github.io/$repo_name/"
        echo "GitHub Pages Link: $github_pages_link"

    - name: Build Hugo site
      env:
        repo_name: $(basename ${{ github.repository }})
      run: |
        cd exampleSite && \
        hugo \
          --themesDir ../.. \
          --baseURL https://${{ github.repository_owner }}.github.io/${{ env.repo_name }}/

    - name: Deploy production 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: ./exampleSite/public