name: Hugo Build

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.117.0'  # Specify your desired Hugo version

    - name: Build Hugo site
      run: |
        cd exampleSite
        hugo --theme hugo-igloo --themesDir ../../  # Adjust the path to your exampleSite folder

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./exampleSite/public  # Adjust the path to your public folder
