name: Hugo Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build color

    # create a matrix from the color data file
    strategy:
        fail-fast: false
        matrix:
          color: 
            - ash   
            - barbie 
            - dune   
            - mint   
            - moss   
            - paper  
            - plum   
            - poppy  
            - pumpkin
            - teal   
            - violet 
            - vlad   
            - water  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.117.0'
        extended: true

    - name: Extract GitHub Pages link
      run: |
        repo="${{ github.repository }}"
        owner=$(echo $repo | sed -n 's/^\(.*\)\/.*/\1/p')
        repo_name=$(echo $repo | sed -n 's/.*\/\([^/]*\)$/\1/p')
        github_pages_link="https://$owner.github.io/$repo_name/"
        echo "gh-pages=$github_pages_link" >> $GITHUB_ENV
  
    - name: Build Hugo
      run: |
        cat exampleSite/hugo.toml | sed -e s/icicle/${{ matrix.color }}/g > exampleSite/hugo_${{ matrix.color }}.toml
        cd exampleSite && \
          hugo \
            --config hugo_${{ matrix.color }}.toml \
            --themesDir ../.. \
            --baseURL ${{ env.gh-pages }}

      # Zip and upload each color-specific build to job artifacts
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.color }}
        path: exampleSite/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3

    - name: Prepare/Collect all websites
      run: |
        mkdir -p ./exampleSite/public/themes/
        for theme in $(find . -name "*.zip"); do
            name=$(basename "$theme" .zip)
            wrkdir=exampleSite/public/themes/${name}
            mkdir -p ${wrkdir}
            unzip ${theme} -d ${wrkdir}
        done

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.117.0'
        extended: true

    - name: Extract GitHub Pages link
      run: |
        repo="${{ github.repository }}"
        owner=$(echo $repo | sed -n 's/^\(.*\)\/.*/\1/p')
        repo_name=$(echo $repo | sed -n 's/.*\/\([^/]*\)$/\1/p')
        github_pages_link="https://$owner.github.io/$repo_name/"
        echo "gh-pages=$github_pages_link" >> $GITHUB_ENV

    # Build main website
    - name: Build Hugo site
      run: |
        cd exampleSite && \
        hugo \
          --themesDir ../.. \
          --baseURL ${{ env.gh-pages }}

    - name: Deploy production
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: ./exampleSite/public
