name: Hugo Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Hugo site with a specific color palette

    # create a matrix from the color data file
    strategy:
        fail-fast: false
        matrix:
          color: 
            - ash   
            - barbie 
            - icicle 
            - dune   
            - mint   
            - moss   
            - paper  
            - plum   
            - poppy  
            - pumpkin
            - teal   
            - violet 
            - vlad   
            - water  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.117.0'
        extended: true

    - name: Extract GitHub Pages link
      run: |
        repo="${{ github.repository }}"
        owner=$(echo $repo | sed -n 's/^\(.*\)\/.*/\1/p')
        repo_name=$(echo $repo | sed -n 's/.*\/\([^/]*\)$/\1/p')
        github_pages_link="https://$owner.github.io/$repo_name/"
        echo "gh-pages=$github_pages_link" >> $GITHUB_ENV
  
    - name: Build Hugo site
      run: |
        # modify the config file with the current color in matrix
        cat exampleSite/hugo.toml | sed -e s/icicle/${{ matrix.color.name }}/g > exampleSite/hugo_${{ matrix.color.name }}.toml
        # Build Hugo site
        cd exampleSite && \
            hugo \
                --config hugo_${{ matrix.color.name }}.toml \
                --themesDir ../.. \
                --destination public/theme/${key} \
                --baseURL ${{ env.gh-pages }}/theme/${{ matrix.color.name }}

    - name: Deploy production
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: ./exampleSite/public
        target-folder: ${{ matrix.color.name }} #deploy to sub-folder