name: Hugo Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.120.4'
        extended: true

    - name: Extract GitHub Pages link
      run: |
        repo="${{ github.repository }}"
        owner=$(echo $repo | sed -n 's/^\(.*\)\/.*/\1/p')
        repo_name=$(echo $repo | sed -n 's/.*\/\([^/]*\)$/\1/p')
        github_pages_link="https://drmowinckels.io/hugo-igloo/"
        echo "gh-pages=$github_pages_link" >> $GITHUB_ENV

    # Build main website
    - name: Build Hugo site
      run: |
        cd exampleSite && \
        hugo \
          --themesDir ../.. \
          --baseURL ${{ env.gh-pages }}

    - name: Build color themes
      run: |
        # Build theme examples
        themes=("ash" "barbie" "dune" "mint" "moss" "paper" "plum" "poppy" "pumpkin" "teal" "violet" "vlad" "water")
        for theme in ${themes[@]} ; do
            echo ++--- $theme ---++
            cat exampleSite/hugo.toml | sed -e "s/icicle/$theme/g" > exampleSite/hugo_$theme.toml
            cp exampleSite/content/slider/$theme/penguin.png exampleSite/content/about/
            cd exampleSite && \
              hugo \
                --config hugo_$theme.toml \
                --themesDir ../.. \
                --baseURL ${{ env.gh-pages }}/themes/$theme \
                --destination public/themes/$theme
            cd -
        done


    - name: Deploy production 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: ./exampleSite/public
